apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-root-username: cm9vdA==
  postgres-root-password: ZGV2b3Bz
  postgres-connection-string: VXNlciBJRD1yb290O1Bhc3N3b3JkPWRldm9wcztTZXJ2ZXI9cG9zdGdyZXMtc2VydmljZTtQb3J0PTU0MzI7RGF0YWJhc2U9VGltZXN0YW1wREI7SW50ZWdyYXRlZFNlY3VyaXR5PXRydWU7