apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: botimpact/devops
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__Default
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-connection-string
---

apiVersion: v1
kind: Service
metadata: 
  name: webservice-service
spec:
  selector:
    app: webservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
---

