name: build-on-push
on: 
  push:
    branches-ignore:
      - main

jobs:
    build-image:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Build Docker image
              run: docker build -t botimpact/devops:$GITHUB_SHA ./DevOps
