name: push-on-pull_request
on: 
  push:
    branches: 
      - main
env:
    DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
    DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build Docker image
        run: docker build -t botimpact/devops:$GITHUB_SHA ./DevOps

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Publish Docker image
        run: docker push botimpact/devops:$GITHUB_SHA

